# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(default=18)),
                ('email', models.EmailField(default='111@qq.com', max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=255, verbose_name='头像')),
                ('count', models.IntegerField(default=1)),
                ('login_suo', models.DateTimeField(auto_now=True)),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=1)),
            ],
        ),
    ]
