# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_login_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='static/upload'),
        ),
    ]
