# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181215_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='avatar',
        ),
        migrations.AddField(
            model_name='login',
            name='header',
            field=models.FileField(default='static/upload/1.png', upload_to='static/upload'),
        ),
    ]
