# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181215_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='header',
            field=models.FileField(default='static/upload/1.png', upload_to='static/user/image'),
        ),
    ]
